# Generated by Django 5.2 on 2025-04-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_points/'),
        ),
    ]
