# Generated by Django 5.2 on 2025-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint', '0002_remove_city_region_touristpoint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
