# Generated by Django 5.2 on 2025-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristpoint',
            name='location',
        ),
    ]
