# Generated by Django 5.2 on 2025-04-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint', '0006_touristpoint_location_lat_touristpoint_location_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.CharField(default='PI', max_length=2),
        ),
    ]
